# Generated by Django 3.1 on 2020-08-28 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200828_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='Misc', max_length=25),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='poster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
